-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.

CREATE TABLE IF NOT EXISTS public.cliente
(
    id serial PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    correo_electronico character varying(100) NOT NULL,
    contraseña character varying(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.producto
(
    id serial PRIMARY KEY,
    nombre character varying(100) NOT NULL,
    precio numeric(10, 2) NOT NULL,
    descripcion text,
    cantidad_en_stock integer
);

CREATE TABLE IF NOT EXISTS public.carrito_de_compras
(
    id serial PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS public.pedido
(
    id serial PRIMARY KEY,
    cliente_id integer NOT NULL,
    fecha date NOT NULL,
    direccion_envio text NOT NULL,
    metodo_pago text NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES public.cliente (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.comentario
(
    id serial PRIMARY KEY,
    cliente_id integer NOT NULL,
    fecha_comentario date NOT NULL,
    contenido text NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES public.cliente (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.tienda
(
    id serial PRIMARY KEY,
    nombre text NOT NULL,
    direccion text NOT NULL
);

CREATE TABLE IF NOT EXISTS public.promocion
(
    id serial PRIMARY KEY,
    producto_id integer NOT NULL,
    descuento integer NOT NULL,
    fecha_inicio date NOT NULL,
    fecha_fin date NOT NULL,
    FOREIGN KEY (producto_id) REFERENCES public.producto (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

CREATE TABLE IF NOT EXISTS public.pedidos_productos
(
    pedido_id integer NOT NULL,
    producto_id integer NOT NULL,
    cantidad integer NOT NULL,
    PRIMARY KEY (pedido_id, producto_id),
    FOREIGN KEY (pedido_id) REFERENCES public.pedido (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY (producto_id) REFERENCES public.producto (id) ON UPDATE NO ACTION ON DELETE NO ACTION
);

ALTER TABLE IF EXISTS public.producto
    ADD tienda_id integer,
    ADD comentario_id integer,
    ADD promocion_id integer,
    ADD FOREIGN KEY (tienda_id) REFERENCES public.tienda (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    ADD FOREIGN KEY (comentario_id) REFERENCES public.comentario (id) ON UPDATE NO ACTION ON DELETE NO ACTION,
    ADD FOREIGN KEY (promocion_id) REFERENCES public.promocion (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
